Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/12/2022
Var
i : inteiro
total : real


Inicio
Escreva("Os numeros multiplos de 3:")
Para i de 1 ate 100 faca
se((i mod 3) = 0) entao
Escreva(i)
fimse
fimpara
Escreva(" ")
Escreva(" ")



total <- (i * 30)
Escreva("Multiplos de 3 multiplicados por 30")

Escreva(total)


Fimalgoritmo